mapping_names = {
 'bitcoin': 'BTC',
 'ethereum': 'ETH',
 'ripple': 'XRP',
 'bitcoin-cash': 'BCH',
 'eos': 'EOS',
 'stellar': 'XLM',
 'litecoin': 'LTC',
 'cardano': 'ADA',
 'tether': 'USDT',
 'iota': 'MIOTA',
 'tron': 'TRX',
 'ethereum-classic': 'ETC',
 'monero': 'XMR',
 'neo': 'NEO',
 'dash': 'DASH',
 'binance-coin': 'BNB',
 'nem': 'XEM',
 'tezos': 'XTZ',
 'zcash': 'ZEC',
 'omisego': 'OMG',
 'vechain': 'VET',
 'qtum': 'QTUM',
 '0x': 'ZRX',
 'bitcoin-gold': 'BTG',
 'bytecoin-bcn': 'BCN',
 'bitshares': 'BTS',
 'lisk': 'LSK',
 'decred': 'DCR',
 'zilliqa': 'ZIL',
 'aeternity': 'AE',
 'maker': 'MKR',
 'digibyte': 'DGB',
 'icon': 'ICX',
 'ontology': 'ONT',
 'dogecoin': 'DOGE',
 'augur': 'REP',
 'steem': 'STEEM',
 'moac': 'MOAC',
 'verge': 'XVG',
 'siacoin': 'SC',
 'bytom': 'BTM',
 'basic-attention-token': 'BAT',
 'bitcoin-diamond': 'BCD',
 'hshare': 'HSR',
 'rchain': 'RHOC',
 'golem-network-tokens': 'GNT',
 'kucoin-shares': 'KCS',
 'nano': 'NANO',
 'stratis': 'STRAT',
 'status': 'SNT',
 'pundi-x': 'NPXS',
 'waves': 'WAVES',
 'populous': 'PPT',
 'mithril': 'MITH',
 'iostoken': 'IOST',
 'maidsafecoin': 'MAID',
 'komodo': 'KMD',
 'digixdao': 'DGD',
 'waltonchain': 'WTC',
 'huobi-token': 'HT',
 'gxchain': 'GXS',
 'kin': 'KIN',
 'aelf': 'ELF',
 'ardor': 'ARDR',
 'wanchain': 'WAN',
 'metaverse': 'ETP',
 'monacoin': 'MONA',
 'aion': 'AION',
 'dentacoin': 'DCN',
 'funfair': 'FUN',
 'bancor': 'BNT',
 'zencash': 'ZEN',
 'holo': 'HOT',
 'decentraland': 'MANA',
 'bitcoin-private': 'BTCP',
 'nebulas-token': 'NAS',
 'monaco': 'MCO',
 'emercoin': 'EMC',
 'wax': 'WAX',
 'dropil': 'DROP',
 'cryptonex': 'CNX',
 'loopring': 'LRC',
 'odem': 'ODE',
 'ark': 'ARK',
 'kyber-network': 'KNC',
 'power-ledger': 'POWR',
 'reddcoin': 'RDD',
 'mybit-token': 'MYB',
 'chainlink': 'LINK',
 'nxt': 'NXT',
 'gas': 'GAS',
 'pivx': 'PIVX',
 'polymath-network': 'POLY',
 'loom-network': 'LOOM',
 'tenx': 'PAY',
 'theta-token': 'THETA',
 'cybermiles': 'CMT',
 'elastos': 'ELA',
 'nuls': 'NULS',
 'bibox-token': 'BIX'
}

list_names = ['bitcoin',
 'ethereum',
 'ripple',
 'bitcoin-cash',
 'eos',
 'stellar',
 'litecoin',
 'cardano',
 'tether',
 'iota',
 'tron',
 'ethereum-classic',
 'monero',
 'neo',
 'dash',
 'binance-coin',
 'nem',
 'tezos',
 'zcash',
 'omisego',
 'vechain',
 'qtum',
 '0x',
 'bitcoin-gold',
 'bytecoin-bcn',
 'bitshares',
 'lisk',
 'decred',
 'zilliqa',
 'aeternity',
 'maker',
 'digibyte',
 'icon',
 'ontology',
 'dogecoin',
 'augur',
 'steem',
 'moac',
 'verge',
 'siacoin',
 'bytom',
 'basic-attention-token',
 'bitcoin-diamond',
 'hshare',
 'rchain',
 'golem-network-tokens',
 'kucoin-shares',
 'nano',
 'stratis',
 'status',
 'pundi-x',
 'waves',
 'populous',
 'mithril',
 'iostoken',
 'maidsafecoin',
 'komodo',
 'digixdao',
 'waltonchain',
 'huobi-token',
 'gxchain',
 'kin',
 'aelf',
 'ardor',
 'wanchain',
 'metaverse',
 'monacoin',
 'aion',
 'dentacoin',
 'funfair',
 'bancor',
 'zencash',
 'holo',
 'decentraland',
 'bitcoin-private',
 'nebulas-token',
 'monaco',
 'emercoin',
 'wax',
 'dropil',
 'cryptonex',
 'loopring',
 'odem',
 'ark',
 'kyber-network',
 'power-ledger',
 'reddcoin',
 'mybit-token',
 'chainlink',
 'nxt',
 'gas',
 'pivx',
 'polymath-network',
 'loom-network',
 'tenx',
 'theta-token',
 'cybermiles',
 'elastos',
 'nuls',
 'bibox-token']

